copyright: Copyright (c) Ultraviolet
repo_url: https://github.com/ultravioletrs/cocos
site_description: Cocos AI SMPC Platform
site_name: Cocos
site_url: https://docs.cocos.ai
edit_uri: ""
theme:
  name: material
  logo: img/logo.png
  favicon: img/logo.png
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - toc:
      permalink: "#"

nav:
  - Overview: index.md
  - Architecture: architecture.md
  - Install: install.md
  - Getting Started: getting-started.md
  - Computations: computations.md
  - Datasets: datasets.md
  - Users: users.md
  - Groups: groups.md
  - Policies: policies.md
  - TEE: tee.md
  - HAL: hal.md
  - Agent: agent.md
  - Attestation: attestation.md
  - CLI: cli.md
  - UI: ui.md
